/**
 * GiveForward geodata — generated from Cities.xlsx and Countries.xlsx
 *
 * SOURCE FILES: stored at frontend/src/lib/geodata/ (Cities.xlsx, Countries.xlsx)
 * To regenerate, run: python3 scripts/generate_geodata.py
 *
 * Usage:
 *   import { COUNTRIES_EN, COUNTRIES_BG, CITIES_EN, CITIES_BG,
 *            BULGARIA_EN, BULGARIA_BG, isBulgaria } from '@/lib/geodata'
 */

/** All country names in English — index-parallel with COUNTRIES_BG */
export const COUNTRIES_EN = [
  "Afghanistan",
  "Albania",
  "Algeria",
  "Andorra",
  "Angola",
  "Antigua and Barbuda",
  "Argentina",
  "Armenia",
  "Australia",
  "Austria",
  "Azerbaijan",
  "Bahamas",
  "Bahrain",
  "Bangladesh",
  "Barbados",
  "Belarus",
  "Belgium",
  "Belize",
  "Benin",
  "Bhutan",
  "Bolivia",
  "Bosnia and Herzegovina",
  "Botswana",
  "Brazil",
  "Brunei",
  "Bulgaria",
  "Burkina Faso",
  "Burundi",
  "Cabo Verde",
  "Cambodia",
  "Cameroon",
  "Canada",
  "Central African Republic",
  "Chad",
  "Chile",
  "China",
  "Colombia",
  "Comoros",
  "Costa Rica",
  "Côte d'Ivoire",
  "Croatia",
  "Cuba",
  "Cyprus",
  "Czechia",
  "Democratic Republic of the Congo",
  "Denmark",
  "Djibouti",
  "Dominica",
  "Dominican Republic",
  "Ecuador",
  "Egypt",
  "El Salvador",
  "Equatorial Guinea",
  "Eritrea",
  "Estonia",
  "Eswatini",
  "Ethiopia",
  "Fiji",
  "Finland",
  "France",
  "Gabon",
  "Gambia",
  "Georgia",
  "Germany",
  "Ghana",
  "Greece",
  "Grenada",
  "Guatemala",
  "Guinea",
  "Guinea-Bissau",
  "Guyana",
  "Haiti",
  "Honduras",
  "Hungary",
  "Iceland",
  "India",
  "Indonesia",
  "Iran",
  "Iraq",
  "Ireland",
  "Israel",
  "Italy",
  "Jamaica",
  "Japan",
  "Jordan",
  "Kazakhstan",
  "Kenya",
  "Kiribati",
  "Kosovo",
  "Kuwait",
  "Kyrgyzstan",
  "Laos",
  "Latvia",
  "Lebanon",
  "Lesotho",
  "Liberia",
  "Libya",
  "Liechtenstein",
  "Lithuania",
  "Luxembourg",
  "Madagascar",
  "Malawi",
  "Malaysia",
  "Maldives",
  "Mali",
  "Malta",
  "Marshall Islands",
  "Mauritania",
  "Mauritius",
  "Mexico",
  "Micronesia",
  "Moldova",
  "Monaco",
  "Mongolia",
  "Montenegro",
  "Morocco",
  "Mozambique",
  "Myanmar",
  "Namibia",
  "Nauru",
  "Nepal",
  "Netherlands",
  "New Zealand",
  "Nicaragua",
  "Niger",
  "Nigeria",
  "North Korea",
  "North Macedonia",
  "Norway",
  "Oman",
  "Pakistan",
  "Palau",
  "Palestine",
  "Panama",
  "Papua New Guinea",
  "Paraguay",
  "Peru",
  "Philippines",
  "Poland",
  "Portugal",
  "Qatar",
  "Republic of the Congo",
  "Romania",
  "Russia",
  "Rwanda",
  "Saint Kitts and Nevis",
  "Saint Lucia",
  "Saint Vincent and the Grenadines",
  "Samoa",
  "San Marino",
  "Sao Tome and Principe",
  "Saudi Arabia",
  "Senegal",
  "Serbia",
  "Seychelles",
  "Sierra Leone",
  "Singapore",
  "Slovakia",
  "Slovenia",
  "Solomon Islands",
  "Somalia",
  "South Africa",
  "South Korea",
  "South Sudan",
  "Spain",
  "Sri Lanka",
  "Sudan",
  "Suriname",
  "Sweden",
  "Switzerland",
  "Syria",
  "Taiwan",
  "Tajikistan",
  "Tanzania",
  "Thailand",
  "Timor-Leste",
  "Togo",
  "Tonga",
  "Trinidad and Tobago",
  "Tunisia",
  "Turkey",
  "Turkmenistan",
  "Tuvalu",
  "Uganda",
  "Ukraine",
  "United Arab Emirates",
  "United Kingdom",
  "United States of America",
  "Uruguay",
  "Uzbekistan",
  "Vanuatu",
  "Vatican City",
  "Venezuela",
  "Vietnam",
  "Yemen",
  "Zambia",
  "Zimbabwe"
]

/** All country names in Bulgarian — index-parallel with COUNTRIES_EN */
export const COUNTRIES_BG = [
  "Афганистан",
  "Албания",
  "Алжир",
  "Андора",
  "Ангола",
  "Антигуа и Барбуда",
  "Аржентина",
  "Армения",
  "Австралия",
  "Австрия",
  "Азербайджан",
  "Бахамски острови",
  "Бахрейн",
  "Бангладеш",
  "Барбадос",
  "Беларус",
  "Белгия",
  "Белиз",
  "Бенин",
  "Бутан",
  "Боливия",
  "Босна и Херцеговина",
  "Ботсвана",
  "Бразилия",
  "Бруней",
  "България",
  "Буркина Фасо",
  "Бурунди",
  "Кабо Верде",
  "Камбоджа",
  "Камерун",
  "Канада",
  "Централноафриканска република",
  "Чад",
  "Чили",
  "Китай",
  "Колумбия",
  "Коморски острови",
  "Коста Рика",
  "Кот д’Ивоар",
  "Хърватия",
  "Куба",
  "Кипър",
  "Чехия",
  "Демократична република Конго",
  "Дания",
  "Джибути",
  "Доминика",
  "Доминиканска република",
  "Еквадор",
  "Египет",
  "Салвадор",
  "Екваториална Гвинея",
  "Еритрея",
  "Естония",
  "Свазиленд",
  "Етиопия",
  "Фиджи",
  "Финландия",
  "Франция",
  "Габон",
  "Гамбия",
  "Грузия",
  "Германия",
  "Гана",
  "Гърция",
  "Гренада",
  "Гватемала",
  "Гвинея",
  "Гвинея-Бисау",
  "Гвиана",
  "Хаити",
  "Хондурас",
  "Унгария",
  "Исландия",
  "Индия",
  "Индонезия",
  "Иран",
  "Ирак",
  "Ирландия",
  "Израел",
  "Италия",
  "Ямайка",
  "Япония",
  "Йордания",
  "Казахстан",
  "Кения",
  "Кирибати",
  "Косово",
  "Кувейт",
  "Киргизстан",
  "Лаос",
  "Латвия",
  "Ливан",
  "Лесото",
  "Либерия",
  "Либия",
  "Лихтенщайн",
  "Литва",
  "Люксембург",
  "Мадагаскар",
  "Малави",
  "Малайзия",
  "Малдиви",
  "Мали",
  "Малта",
  "Маршалови острови",
  "Мавритания",
  "Мавриций",
  "Мексико",
  "Микронезия",
  "Молдова",
  "Монако",
  "Монголия",
  "Черна гора",
  "Мароко",
  "Мозамбик",
  "Мианмар",
  "Намибия",
  "Науру",
  "Непал",
  "Нидерландия",
  "Нова Зеландия",
  "Никарагуа",
  "Нигер",
  "Нигерия",
  "Северна Корея",
  "Северна Македония",
  "Норвегия",
  "Оман",
  "Пакистан",
  "Палау",
  "Палестина",
  "Панама",
  "Папуа Нова Гвинея",
  "Парагвай",
  "Перу",
  "Филипини",
  "Полша",
  "Португалия",
  "Катар",
  "Република Конго",
  "Румъния",
  "Русия",
  "Руанда",
  "Сейнт Китс и Невис",
  "Сейнт Лусия",
  "Сейнт Винсент и Гренадини",
  "Самоа",
  "Сан Марино",
  "Сао Томе и Принсипи",
  "Саудитска Арабия",
  "Сенегал",
  "Сърбия",
  "Сейшели",
  "Сиера Леоне",
  "Сингапур",
  "Словакия",
  "Словения",
  "Соломонови острови",
  "Сомалия",
  "Южна Африка",
  "Южна Корея",
  "Южен Судан",
  "Испания",
  "Шри Ланка",
  "Судан",
  "Суринам",
  "Швеция",
  "Швейцария",
  "Сирия",
  "Тайван",
  "Таджикистан",
  "Танзания",
  "Тайланд",
  "Източен Тимор",
  "Того",
  "Тонга",
  "Тринидад и Тобаго",
  "Тунис",
  "Турция",
  "Туркменистан",
  "Тувалу",
  "Уганда",
  "Украйна",
  "Обединени арабски емирства",
  "Обединено кралство",
  "Съединени американски щати",
  "Уругвай",
  "Узбекистан",
  "Вануату",
  "Ватикан",
  "Венецуела",
  "Виетнам",
  "Йемен",
  "Замбия",
  "Зимбабве"
]

/** All Bulgarian city names in English — index-parallel with CITIES_BG */
export const CITIES_EN = [
  "Aytos",
  "Aksakovo",
  "Alfatar",
  "Antonovo",
  "Apriltsi",
  "Ardino",
  "Asenovgrad",
  "Aheloy",
  "Ahtopol",
  "Balchik",
  "Bankya",
  "Bansko",
  "Banya",
  "Batak",
  "Belene",
  "Belitsa",
  "Belogradchik",
  "Beloslav",
  "Berkovitsa",
  "Blagoevgrad",
  "Bobov Dol",
  "Boboshevo",
  "Bozhurishte",
  "Bolyarovo",
  "Borovo",
  "Botevgrad",
  "Bratsigovo",
  "Bregovo",
  "Breznik",
  "Brezovo",
  "Brusartsi",
  "Burgas",
  "Buhovo",
  "Byala (Varna)",
  "Byala (Ruse)",
  "Varna",
  "Veliki Preslav",
  "Veliko Tarnovo",
  "Velingrad",
  "Vetovo",
  "Vidin",
  "Vratsa",
  "Valchedram",
  "Valchi Dol",
  "Varbitsa",
  "Varshets",
  "Gabrovo",
  "General Toshevo",
  "Glavinitsa",
  "Glodzhevo",
  "Godech",
  "Gorna Oryahovitsa",
  "Gotse Delchev",
  "Gramada",
  "Gulyantsi",
  "Gurkovo",
  "Dve Mogili",
  "Devin",
  "Devnya",
  "Dimitrovgrad",
  "Dobrinishte",
  "Dobrich",
  "Dolna Banya",
  "Dolna Mitropoliya",
  "Dolni Dabnik",
  "Dolni Chiflik",
  "Dospat",
  "Dragoman",
  "Dryanovo",
  "Dulovo",
  "Dunavtsi",
  "Dupnitsa",
  "Elena",
  "Elin Pelin",
  "Elhovo",
  "Etropole",
  "Zavet",
  "Zlataritsa",
  "Zlatitsa",
  "Zlatograd",
  "Ivaylovgrad",
  "Ignatievo",
  "Iskar",
  "Isperih",
  "Ihtiman",
  "Kavarna",
  "Kazanlak",
  "Kalofer",
  "Kameno",
  "Kaolinovo",
  "Karlovo",
  "Karnobat",
  "Kaspichan",
  "Kermen",
  "Kilifarevo",
  "Knezha",
  "Kozloduy",
  "Koynare",
  "Koprivshtitsa",
  "Kostandovo",
  "Kostenets",
  "Kostinbrod",
  "Kotel",
  "Kocherinovo",
  "Kresna",
  "Krichim",
  "Krumovgrad",
  "Kubrat",
  "Kuklen",
  "Kula",
  "Kardzhali",
  "Kyustendil",
  "Levski",
  "Letnitsa",
  "Lovech",
  "Loznitsa",
  "Lom",
  "Lukovit",
  "Laki",
  "Madan",
  "Madzharovo",
  "Malko Tarnovo",
  "Marten",
  "Mezdra",
  "Melnik",
  "Merichleri",
  "Miziya",
  "Momin Prohod",
  "Momchilgrad",
  "Montana",
  "Maglizh",
  "Nedelino",
  "Nesebar",
  "Nikolaevo",
  "Nikopol",
  "Nova Zagora",
  "Novi Iskar",
  "Novi Pazar",
  "Obzor",
  "Omurtag",
  "Opaka",
  "Oryahovo",
  "Pavel Banya",
  "Pavlikeni",
  "Pazardzhik",
  "Panagyurishte",
  "Pernik",
  "Perushtitsa",
  "Petrich",
  "Peshtera",
  "Pirdop",
  "Pleven",
  "Plovdiv",
  "Polski Trambesh",
  "Pomorie",
  "Popovo",
  "Pravets",
  "Provadia",
  "Parvomay",
  "Radnevo",
  "Radomir",
  "Razgrad",
  "Razlog",
  "Rakitovo",
  "Rila",
  "Roman",
  "Rudozem",
  "Ruse",
  "Sadovo",
  "Samokov",
  "Sandanski",
  "Svilengrad",
  "Svishtov",
  "Svoge",
  "Sevlievo",
  "Senovo",
  "Septemvri",
  "Silistra",
  "Simeonovgrad",
  "Simitli",
  "Slavyanovo",
  "Sliven",
  "Slivnitsa",
  "Smolyan",
  "Smyadovo",
  "Sozopol",
  "Sofia",
  "Sredets",
  "Stamboliyski",
  "Stara Zagora",
  "Strazhitsa",
  "Straldzha",
  "Strelcha",
  "Strumyani",
  "Suvorovo",
  "Sungurlare",
  "Suhindol",
  "Saedinenie",
  "Sarnitsa",
  "Tvarditsa",
  "Tervel",
  "Teteven",
  "Topolovgrad",
  "Troyan",
  "Tran",
  "Trastenik",
  "Tryavna",
  "Targovishte",
  "Hadzhidimovo",
  "Harmanli",
  "Haskovo",
  "Hisarya",
  "Tsar Kaloyan",
  "Tsarevo",
  "Chepelare",
  "Chernomorets",
  "Cherven Bryag",
  "Chiprovtsi",
  "Chirpan",
  "Shabla",
  "Shivachevo",
  "Shipka",
  "Shumen",
  "Yablanitsa",
  "Yakoruda",
  "Yambol",
  "Online",
  "Other"
]

/** All Bulgarian city names in Bulgarian — index-parallel with CITIES_EN */
export const CITIES_BG = [
  "Айтос",
  "Аксаково",
  "Алфатар",
  "Антоново",
  "Априлци",
  "Ардино",
  "Асеновград",
  "Ахелой",
  "Ахтопол",
  "Балчик",
  "Банкя",
  "Банско",
  "Баня",
  "Батак",
  "Белене",
  "Белица",
  "Белоградчик",
  "Белослав",
  "Берковица",
  "Благоевград",
  "Бобов дол",
  "Бобошево",
  "Божурище",
  "Болярово",
  "Борово",
  "Ботевград",
  "Брацигово",
  "Брегово",
  "Брезник",
  "Брезово",
  "Брусарци",
  "Бургас",
  "Бухово",
  "Бяла (Варна)",
  "Бяла (Русе)",
  "Варна",
  "Велики Преслав",
  "Велико Търново",
  "Велинград",
  "Ветово",
  "Видин",
  "Враца",
  "Вълчедръм",
  "Вълчи дол",
  "Върбица",
  "Вършец",
  "Габрово",
  "Генерал Тошево",
  "Главиница",
  "Глоджево",
  "Годеч",
  "Горна Оряховица",
  "Гоце Делчев",
  "Грамада",
  "Гулянци",
  "Гурково",
  "Две могили",
  "Девин",
  "Девня",
  "Димитровград",
  "Добринище",
  "Добрич",
  "Долна баня",
  "Долна Митрополия",
  "Долни Дъбник",
  "Долни чифлик",
  "Доспат",
  "Драгоман",
  "Дряново",
  "Дулово",
  "Дунавци",
  "Дупница",
  "Елена",
  "Елин Пелин",
  "Елхово",
  "Етрополе",
  "Завет",
  "Златарица",
  "Златица",
  "Златоград",
  "Ивайловград",
  "Игнатиево",
  "Искър",
  "Исперих",
  "Ихтиман",
  "Каварна",
  "Казанлък",
  "Калофер",
  "Камено",
  "Каолиново",
  "Карлово",
  "Карнобат",
  "Каспичан",
  "Кермен",
  "Килифарево",
  "Кнежа",
  "Козлодуй",
  "Койнаре",
  "Копривщица",
  "Костандово",
  "Костенец",
  "Костинброд",
  "Котел",
  "Кочериново",
  "Кресна",
  "Кричим",
  "Крумовград",
  "Кубрат",
  "Куклен",
  "Кула",
  "Кърджали",
  "Кюстендил",
  "Левски",
  "Летница",
  "Ловеч",
  "Лозница",
  "Лом",
  "Луковит",
  "Лъки",
  "Мадан",
  "Маджарово",
  "Малко Търново",
  "Мартен",
  "Мездра",
  "Мелник",
  "Меричлери",
  "Мизия",
  "Момин проход",
  "Момчилград",
  "Монтана",
  "Мъглиж",
  "Неделино",
  "Несебър",
  "Николаево",
  "Никопол",
  "Нова Загора",
  "Нови Искър",
  "Нови пазар",
  "Обзор",
  "Омуртаг",
  "Опака",
  "Оряхово",
  "Павел баня",
  "Павликени",
  "Пазарджик",
  "Панагюрище",
  "Перник",
  "Перущица",
  "Петрич",
  "Пещера",
  "Пирдоп",
  "Плевен",
  "Пловдив",
  "Полски Тръмбеш",
  "Поморие",
  "Попово",
  "Правец",
  "Провадия",
  "Първомай",
  "Раднево",
  "Радомир",
  "Разград",
  "Разлог",
  "Ракитово",
  "Рила",
  "Роман",
  "Рудозем",
  "Русе",
  "Садово",
  "Самоков",
  "Сандански",
  "Свиленград",
  "Свищов",
  "Своге",
  "Севлиево",
  "Сеново",
  "Септември",
  "Силистра",
  "Симеоновград",
  "Симитли",
  "Славяново",
  "Сливен",
  "Сливница",
  "Смолян",
  "Смядово",
  "Созопол",
  "София",
  "Средец",
  "Стамболийски",
  "Стара Загора",
  "Стражица",
  "Стралджа",
  "Стрелча",
  "Струмяни",
  "Суворово",
  "Сунгурларе",
  "Сухиндол",
  "Съединение",
  "Сърница",
  "Твърдица",
  "Тервел",
  "Тетевен",
  "Тополовград",
  "Троян",
  "Трън",
  "Тръстеник",
  "Трявна",
  "Търговище",
  "Хаджидимово",
  "Харманли",
  "Хасково",
  "Хисаря",
  "Цар Калоян",
  "Царево",
  "Чепеларе",
  "Черноморец",
  "Червен бряг",
  "Чипровци",
  "Чирпан",
  "Шабла",
  "Шивачево",
  "Шипка",
  "Шумен",
  "Ябланица",
  "Якоруда",
  "Ямбол",
  "Онлайн",
  "Друго"
]

/** Canonical English name for Bulgaria */
export const BULGARIA_EN = 'Bulgaria'

/** Canonical Bulgarian name for Bulgaria */
export const BULGARIA_BG = 'България'

/**
 * Returns true when the given value (EN or BG) represents Bulgaria.
 * Case-insensitive for safety.
 */
export function isBulgaria(val) {
  if (!val) return false
  const v = val.trim().toLowerCase()
  return v === 'bulgaria' || v === 'българия'
}

/**
 * Given a country name in either language, return the paired name.
 * Returns null if not found.
 */
export function pairCountry(val) {
  if (!val) return null
  const v = val.trim()
  let idx = COUNTRIES_EN.indexOf(v)
  if (idx >= 0) return COUNTRIES_BG[idx]
  idx = COUNTRIES_BG.indexOf(v)
  if (idx >= 0) return COUNTRIES_EN[idx]
  return null
}

/**
 * Given an EN city name, return the BG name (for Bulgarian cities).
 */
export function pairCityEN(en) {
  const idx = CITIES_EN.indexOf(en)
  return idx >= 0 ? CITIES_BG[idx] : null
}

/**
 * Given a BG city name, return the EN name (for Bulgarian cities).
 */
export function pairCityBG(bg) {
  const idx = CITIES_BG.indexOf(bg)
  return idx >= 0 ? CITIES_EN[idx] : null
}
